import { z } from 'zod';

/**
 * Runtime env schema.
 *
 * Production posture: MONGO_URI, REDIS_URL, and the two JWT PEMs are
 * HARD-REQUIRED. Absence causes `process.exit(1)` at boot — no silent
 * fallback to dev defaults leaks into prod.
 *
 * Dev/test posture: MONGO_URI and REDIS_URL fall back to the local
 * docker-compose addresses. JWT keys fall back to an ephemeral RSA
 * pair generated by `src/shared/jwt/signer.ts` (which logs a warning).
 */
const EnvSchema = z
  .object({
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    PORT: z.coerce.number().int().positive().default(4000),
    LOG_LEVEL: z
      .enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent'])
      .default('info'),

    MONGO_URI: z.string().min(1).optional(),
    REDIS_URL: z.string().min(1).optional(),

    JWT_PRIVATE_KEY_PEM: z.string().min(1).optional(),
    JWT_PUBLIC_KEY_PEM: z.string().min(1).optional(),

    OTP_SENDER: z.enum(['dev-console', 'msg91']).default('dev-console'),
    MSG91_AUTH_KEY: z.string().optional(),
    MSG91_TEMPLATE_ID: z.string().optional(),
    MSG91_SENDER_ID: z.string().optional(),

    AWS_REGION: z.string().min(1).optional(),
    KMS_KEY_ID: z.string().min(1).optional(),
    REDEEM_CODE_HASH_SECRET: z.string().min(32).optional(),
  })
  .superRefine((data, ctx) => {
    if (data.NODE_ENV !== 'production') return;
    const requiredInProd = [
      'MONGO_URI',
      'REDIS_URL',
      'JWT_PRIVATE_KEY_PEM',
      'JWT_PUBLIC_KEY_PEM',
      'AWS_REGION',
      'KMS_KEY_ID',
      'REDEEM_CODE_HASH_SECRET',
    ] as const;
    for (const key of requiredInProd) {
      if (!data[key]) {
        ctx.addIssue({
          code: 'custom',
          path: [key],
          message: `${key} is required in production`,
        });
      }
    }
  })
  .transform((data) => ({
    ...data,
    // Dev/test defaults applied only after refine has passed. In
    // production these fallbacks are unreachable because refine would
    // have already failed the parse.
    MONGO_URI: data.MONGO_URI ?? 'mongodb://localhost:27017/cashfb?directConnection=true',
    REDIS_URL: data.REDIS_URL ?? 'redis://localhost:6379',
  }));

export type Env = z.infer<typeof EnvSchema>;

const parsed = EnvSchema.safeParse(process.env);

if (!parsed.success) {
  const issues = parsed.error.issues
    .map((i) => `  - ${i.path.join('.') || '(root)'}: ${i.message}`)
    .join('\n');
  process.stderr.write(`[env] Invalid environment configuration:\n${issues}\n`);
  process.exit(1);
}

export const env: Env = parsed.data;
