import { z } from 'zod';

/**
 * Runtime env schema.
 *
 * Production posture: MONGO_URI, REDIS_URL, and the two JWT PEMs are
 * HARD-REQUIRED. Absence causes `process.exit(1)` at boot — no silent
 * fallback to dev defaults leaks into prod.
 *
 * Dev/test posture: MONGO_URI and REDIS_URL fall back to the local
 * docker-compose addresses. JWT keys fall back to an ephemeral RSA
 * pair generated by `src/shared/jwt/signer.ts` (which logs a warning).
 */
const EnvSchema = z
  .object({
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    PORT: z.coerce.number().int().positive().default(4000),
    LOG_LEVEL: z
      .enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent'])
      .default('info'),

    MONGO_URI: z.string().min(1).optional(),
    REDIS_URL: z.string().min(1).optional(),

    JWT_PRIVATE_KEY_PEM: z.string().min(1).optional(),
    JWT_PUBLIC_KEY_PEM: z.string().min(1).optional(),

    OTP_SENDER: z.enum(['dev-console', 'msg91']).default('dev-console'),
    MSG91_AUTH_KEY: z.string().optional(),
    MSG91_TEMPLATE_ID: z.string().optional(),
    MSG91_SENDER_ID: z.string().optional(),

    AWS_REGION: z.string().min(1).optional(),
    KMS_KEY_ID: z.string().min(1).optional(),
    REDEEM_CODE_HASH_SECRET: z.string().min(32).optional(),

    RAZORPAY_KEY_ID: z.string().min(1).optional(),
    RAZORPAY_KEY_SECRET: z.string().min(1).optional(),
    RAZORPAY_WEBHOOK_SECRET: z.string().min(16).optional(),

    MERCHANT_LEGAL_NAME: z.string().min(1).optional(),
    MERCHANT_GSTIN: z
      .string()
      .regex(/^[0-9A-Z]{15}$/, 'GSTIN must be 15 alphanumeric chars')
      .optional(),
    MERCHANT_STATE_CODE: z
      .string()
      .regex(/^IN-[A-Z]{2}$/, 'State must be ISO 3166-2:IN code like IN-MH')
      .optional(),
    MERCHANT_ADDRESS_LINE1: z.string().min(1).optional(),
    MERCHANT_PIN: z
      .string()
      .regex(/^[0-9]{6}$/, 'PIN must be 6 digits')
      .optional(),

    S3_INVOICES_BUCKET: z.string().min(1).optional(),
    SES_FROM_EMAIL: z.string().email().optional(),
    SES_REPLY_TO_EMAIL: z.string().email().optional(),

    BULL_DASHBOARD_PATH: z.string().min(1).default('/admin/queues'),
    WORKER_CONCURRENCY: z.coerce.number().int().min(1).max(100).default(10),
    BULL_DLQ_NAME: z.string().min(1).default('dlq'),

    // Sentry. All optional — absent DSN short-circuits Sentry.init to
    // a no-op so local / CI boots stay unaffected. SENTRY_RELEASE is
    // injected at image build time via the Dockerfile GIT_SHA ARG.
    SENTRY_DSN: z.string().url().optional(),
    SENTRY_ENVIRONMENT: z.string().min(1).optional(),
    SENTRY_RELEASE: z.string().min(1).optional(),
  })
  .superRefine((data, ctx) => {
    if (data.NODE_ENV !== 'production') return;
    const requiredInProd = [
      'MONGO_URI',
      'REDIS_URL',
      'JWT_PRIVATE_KEY_PEM',
      'JWT_PUBLIC_KEY_PEM',
      'AWS_REGION',
      'KMS_KEY_ID',
      'REDEEM_CODE_HASH_SECRET',
      'RAZORPAY_KEY_ID',
      'RAZORPAY_KEY_SECRET',
      'RAZORPAY_WEBHOOK_SECRET',
      'MERCHANT_LEGAL_NAME',
      'MERCHANT_GSTIN',
      'MERCHANT_STATE_CODE',
      'MERCHANT_ADDRESS_LINE1',
      'MERCHANT_PIN',
      'S3_INVOICES_BUCKET',
      'SES_FROM_EMAIL',
    ] as const;
    for (const key of requiredInProd) {
      if (!data[key]) {
        ctx.addIssue({
          code: 'custom',
          path: [key],
          message: `${key} is required in production`,
        });
      }
    }
  })
  .transform((data) => ({
    ...data,
    // Dev/test defaults applied only after refine has passed. In
    // production these fallbacks are unreachable because refine would
    // have already failed the parse.
    //
    // Non-standard ports on purpose: docker-compose.dev.yml binds
    // mongo → 27018 and redis → 6380 to avoid colliding with Homebrew
    // mongod / redis on macOS dev machines.
    //
    // directConnection=true is REQUIRED for single-node docker replsets
    // when connecting from the host. The replset self-advertises as
    // localhost:27017 (container-internal), which breaks SDAM discovery
    // from the host where we connect via 27018. directConnection bypasses
    // SDAM — the driver talks to the explicit socket. Single-member
    // replsets still provide session + transaction capability.
    // DO NOT add replicaSet=rs0 — it re-enables SDAM and hangs.
    MONGO_URI: data.MONGO_URI ?? 'mongodb://localhost:27018/cashfb?directConnection=true',
    REDIS_URL: data.REDIS_URL ?? 'redis://localhost:6380',
  }));

export type Env = z.infer<typeof EnvSchema>;

const parsed = EnvSchema.safeParse(process.env);

if (!parsed.success) {
  const issues = parsed.error.issues
    .map((i) => `  - ${i.path.join('.') || '(root)'}: ${i.message}`)
    .join('\n');
  process.stderr.write(`[env] Invalid environment configuration:\n${issues}\n`);
  process.exit(1);
}

export const env: Env = parsed.data;
